env:
  es6: true
  browser: true
  commonjs: true
  jest: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

extends: ['htmlacademy/es6', 'plugin:react/recommended']

plugins: ['react']

settings:
  react:
    version: '16'
